### ISSUE TITLE
Install

### ISSUE THREAD

**Issue by polzy** [LeTchang/PoGoTool#2]
Hi, 
It's possible to install without mac OS  ? by cydia  ? 

Thanks

**Comment by LeTchang** [comment]
You need Xcode to compile the project. I don't know if it works on Cydia.

**Comment by polzy** [comment]
it's possible to compil in iOS for me plz ? :/

**Comment by LeTchang** [comment]
Sorry Polzy, the app doesn't work since recent updates from Niantic. I don't have time to work on it now I have a full time job.

But take care with these app using Niantic's API because now you can get insta banned.
